name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm run build:npm 
      - name: Check version
        id: check-version
        run: |
          LATEST_VERSION=$(npm view . version)
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$LATEST_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "::set-output name=publish::true"
          fi
      - name: Publish to npm
        if: steps.check-version.outputs.publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}